import type { ModelCapabilityProfile } from '../../types/capability'

const textOnlyLlmInputs = [{ id: 'prompt', modality: 'text' as const, max_count: 1 }]
const textOut = [{ modality: 'text' as const }]

const deepseekReasoning: ModelCapabilityProfile['reasoning'] = {
  control_kind: 'effort_levels',
  ui_preset: 'off_balanced_deep',
  output_field: 'reasoning_content',
  preset_levels: {
    off: { extra_body: { thinking: { type: 'disabled' } } },
    balanced: {
      reasoning_effort: 'high',
      extra_body: { thinking: { type: 'enabled' } },
    },
    deep: {
      reasoning_effort: 'max',
      extra_body: { thinking: { type: 'enabled' } },
    },
  },
  warnings: ['深度档建议提高 max_tokens 避免推理截断'],
}

export const BUILTIN_PROFILES: ModelCapabilityProfile[] = [
  {
    profile_key: 'deepseek-v4-flash',
    provider: 'openai_compatible',
    model_pattern: 'deepseek-v4-flash',
    kind: 'llm',
    display_name: 'DeepSeek V4 Flash',
    config_ids: ['deepseek-v4-flash', 'deepseek'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: deepseekReasoning,
    aliases: [
      {
        deprecated_id: 'deepseek-chat',
        maps_to: 'deepseek-v4-flash',
        runtime_default: 'off',
        sunset: '2026-07-24T15:59:00Z',
        note: '路由至 V4 Flash 非思考模式',
      },
      {
        deprecated_id: 'deepseek-reasoner',
        maps_to: 'deepseek-v4-flash',
        runtime_default: 'balanced',
        sunset: '2026-07-24T15:59:00Z',
        note: '路由至 V4 Flash 思考模式',
      },
    ],
    confidence: 'documented',
    source: 'builtin',
    doc_url: 'https://api-docs.deepseek.com/quick_start/pricing',
    version: 1,
  },
  {
    profile_key: 'deepseek-v4-pro',
    provider: 'openai_compatible',
    model_pattern: 'deepseek-v4-pro',
    kind: 'llm',
    display_name: 'DeepSeek V4 Pro',
    config_ids: ['deepseek-v4-pro'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: deepseekReasoning,
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'gpt-4o',
    provider: 'openai_compatible',
    model_pattern: 'gpt-4o',
    kind: 'llm',
    display_name: 'GPT-4o',
    config_ids: ['gpt-4o'],
    inputs: [
      { id: 'prompt', modality: 'text', max_count: 1 },
      { id: 'image', modality: 'image', max_count: 10 },
    ],
    outputs: textOut,
    reasoning: { control_kind: 'none', ui_preset: 'hidden' },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'o3-mini',
    provider: 'openai_compatible',
    model_pattern: 'o3-mini',
    kind: 'llm',
    display_name: 'OpenAI o3-mini',
    config_ids: ['o3-mini'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: {
      control_kind: 'always_reasoning',
      ui_preset: 'off_balanced_deep',
      preset_levels: {
        off: { reasoning_effort: 'low' },
        balanced: { reasoning_effort: 'medium' },
        deep: { reasoning_effort: 'high' },
      },
      warnings: ['该模型总会进行推理；「快速」为最低强度'],
    },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'claude-sonnet-4',
    provider: 'anthropic',
    model_pattern: 'claude-sonnet-4*',
    kind: 'llm',
    display_name: 'Claude Sonnet 4',
    config_ids: ['claude-sonnet-4'],
    inputs: [
      { id: 'prompt', modality: 'text', max_count: 1 },
      { id: 'image', modality: 'image', max_count: 20 },
    ],
    outputs: textOut,
    reasoning: {
      control_kind: 'adaptive_effort',
      ui_preset: 'off_balanced_deep',
      preset_levels: {
        off: { thinking: { type: 'adaptive' }, output_config: { effort: 'low' } },
        balanced: { thinking: { type: 'adaptive' }, output_config: { effort: 'medium' } },
        deep: { thinking: { type: 'adaptive' }, output_config: { effort: 'high' } },
      },
    },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'gemini-2.5-flash',
    provider: 'google_gemini',
    model_pattern: 'gemini-2.5-flash',
    kind: 'llm',
    display_name: 'Gemini 2.5 Flash',
    config_ids: ['gemini-2.5-flash'],
    inputs: [
      { id: 'prompt', modality: 'text', max_count: 1 },
      { id: 'image', modality: 'image', max_count: 10 },
      { id: 'video', modality: 'video', max_count: 1 },
      { id: 'audio', modality: 'audio', max_count: 1 },
    ],
    outputs: textOut,
    reasoning: {
      control_kind: 'budget_tokens',
      ui_preset: 'off_balanced_deep',
      preset_levels: {
        off: { thinking_config: { thinking_budget: 0 } },
        balanced: { thinking_config: { thinking_budget: -1 } },
        deep: { thinking_config: { thinking_budget: 8192 } },
      },
    },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'gemini-2.5-pro',
    provider: 'google_gemini',
    model_pattern: 'gemini-2.5-pro',
    kind: 'llm',
    display_name: 'Gemini 2.5 Pro',
    config_ids: ['gemini-2.5-pro'],
    inputs: [
      { id: 'prompt', modality: 'text', max_count: 1 },
      { id: 'image', modality: 'image', max_count: 10 },
    ],
    outputs: textOut,
    reasoning: {
      control_kind: 'budget_tokens',
      ui_preset: 'off_balanced_deep',
      preset_levels: {
        off: { thinking_config: { thinking_budget: 128 } },
        balanced: { thinking_config: { thinking_budget: -1 } },
        deep: { thinking_config: { thinking_budget: 8192 } },
      },
      warnings: ['该模型无法完全关闭思考；「快速」为最低预算'],
    },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'qwen-max',
    provider: 'openai_compatible',
    model_pattern: 'qwen-max',
    kind: 'llm',
    display_name: '通义千问 Max',
    config_ids: ['qwen3', 'qwen-max'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: {
      control_kind: 'hybrid_toggle',
      ui_preset: 'off_balanced_deep',
      preset_levels: {
        off: { extra_body: { enable_thinking: false } },
        balanced: { extra_body: { enable_thinking: true } },
        deep: { extra_body: { enable_thinking: true, thinking_budget: 8192 } },
      },
      stream_required_when_enabled: true,
    },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'glm-4-flash',
    provider: 'openai_compatible',
    model_pattern: 'glm-4-flash',
    kind: 'llm',
    display_name: 'GLM-4 Flash',
    config_ids: ['glm-4'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: {
      control_kind: 'hybrid_toggle',
      ui_preset: 'off_balanced_deep',
      preset_levels: {
        off: { thinking: { type: 'disabled' } },
        balanced: { thinking: { type: 'enabled' } },
        deep: { thinking: { type: 'enabled' } },
      },
    },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'kimi-k2-instruct',
    provider: 'openai_compatible',
    model_pattern: 'kimi-k2-instruct',
    kind: 'llm',
    display_name: 'Kimi K2 Instruct',
    config_ids: ['kimi-k2-instruct'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: { control_kind: 'none', ui_preset: 'hidden' },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'kimi-k2-thinking',
    provider: 'openai_compatible',
    model_pattern: 'kimi-k2-thinking',
    kind: 'llm',
    display_name: 'Kimi K2 Thinking',
    config_ids: ['kimi-k2-thinking'],
    inputs: textOnlyLlmInputs,
    outputs: textOut,
    reasoning: { control_kind: 'separate_model', ui_preset: 'model_implied' },
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'seedream-4-5',
    provider: 'volcengine_ark',
    model_pattern: 'doubao-seedream-4-5*',
    kind: 'image',
    display_name: 'Seedream 4.5',
    config_ids: ['seedream-4-5'],
    inputs: [
      { id: 'prompt', modality: 'text', required: true, max_count: 1 },
      { id: 'reference_image', modality: 'image', max_count: 4 },
    ],
    outputs: [{ modality: 'image' }],
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'seedream-4-0',
    provider: 'volcengine_ark',
    model_pattern: 'doubao-seedream-4-0*',
    kind: 'image',
    display_name: 'Seedream 4.0',
    config_ids: ['seedream-4-0'],
    inputs: [
      { id: 'prompt', modality: 'text', required: true, max_count: 1 },
      { id: 'reference_image', modality: 'image', max_count: 4 },
    ],
    outputs: [{ modality: 'image' }],
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'dall-e-3',
    provider: 'openai_compatible',
    model_pattern: 'dall-e-3',
    kind: 'image',
    display_name: 'DALL-E 3',
    config_ids: ['dall-e-3'],
    inputs: [{ id: 'prompt', modality: 'text', required: true, max_count: 1 }],
    outputs: [{ modality: 'image' }],
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'seedance-1-0-pro-fast',
    provider: 'volcengine_ark',
    model_pattern: 'doubao-seedance-1-0-pro-fast*',
    kind: 'video',
    display_name: 'Seedance 1.0 Pro Fast',
    config_ids: ['seedance-1-0-pro-fast'],
    inputs: [
      { id: 'prompt', modality: 'text', max_count: 1 },
      { id: 'first_frame', modality: 'image', max_count: 1 },
    ],
    outputs: [{ modality: 'video', async: true, poll_required: true }],
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
  {
    profile_key: 'seedance-2-0',
    provider: 'volcengine_ark',
    model_pattern: 'doubao-seedance-2-0*',
    kind: 'video',
    display_name: 'Seedance 2.0',
    config_ids: ['seedance-2-0', 'seedance-2-0-fast'],
    inputs: [
      { id: 'prompt', modality: 'text', max_count: 1 },
      { id: 'first_frame', modality: 'image', max_count: 1 },
      { id: 'last_frame', modality: 'image', max_count: 1 },
      { id: 'reference_image', modality: 'image', max_count: 9 },
      { id: 'reference_video', modality: 'video', max_count: 1 },
      { id: 'reference_audio', modality: 'audio', max_count: 1 },
    ],
    outputs: [{ modality: 'video', async: true, poll_required: true }],
    confidence: 'documented',
    source: 'builtin',
    version: 1,
  },
]

export const CATALOG_VERSION = 1
